name: food_label_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^0.1.7
  http: ^0.12.0+2
  equatable: ^0.6.1
  flutter_bloc: ^2.0.0
  shared_preferences: ^0.5.4+3
  dartz: ^0.8.8
  provider: ^3.1.0+1
  data_connection_checker: ^0.3.4
  get_it: ^3.0.3

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  bloc_test: ^2.1.0

flutter:
  uses-material-design: true
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
