name: scaneat
description: ScanEat Mobile App.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  equatable: ^0.6.1
  flutter_bloc: ^2.0.0
  shared_preferences: ^0.5.4+3
  dartz: ^0.8.8
  provider: ^3.1.0+1
  data_connection_checker: ^0.3.4
  get_it: ^3.0.3
  flutter_camera_ml_vision: ^2.2.4
  firebase_ml_vision: ^0.9.3+3
  camera: ^0.5.6+3

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  bloc_test: ^2.1.0

flutter:
  uses-material-design: true
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins-Regular.ttf
        - asset: lib/assets/fonts/Poppins-SemiBold.ttf
        - asset: lib/assets/fonts/Poppins-Bold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
