name: scaneat
description: ScanEat Mobile App.
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+3
  equatable: ^1.0.1
  flutter_bloc: ^3.1.0
  shared_preferences: ^0.5.6
  dartz: ^0.8.8
  provider: ^4.0.1
  data_connection_checker: ^0.3.4
  get_it: ^4.0.1
  flutter_camera_ml_vision: ^2.2.5
  firebase_ml_vision: ^0.9.3+5
  camera: ^0.5.7+3
  flare_flutter: ^1.8.3
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.17.0
  smooth_page_indicator: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  bloc_test: ^3.0.0
  flutter_launcher_icons: ^0.7.4

flutter:
  uses-material-design: true
  # example:
  assets:
    - lib/assets/animations/
    - lib/assets/icon/logo.png
    - lib/assets/icon/test.jpg
  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Poppins-Bold.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icon/app.png"
